### ISSUE TITLE
after setup there are some errors

### ISSUE THREAD

**Issue by ghost** [HexNio/ssl_pinning_remover#1]
So when i am trying to run
`ssl_pinning_remover -i test.apk -v`
this will show as output
`Traceback (most recent call last):
  File "c:\users\----------\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\----------\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\----------\AppData\Local\Programs\Python\Python38-32\Scripts\ssl_pinning_remover.exe\__main__.py", line 4, in <module>
  File "c:\users\----------\appdata\local\programs\python\python38-32\lib\site-packages\ssl_pinning_remover\ssl_pinning_remover.py", line 5, in <module>
    from .core import core
  File "c:\users\----------\appdata\local\programs\python\python38-32\lib\site-packages\ssl_pinning_remover\core\core.py", line 4, in <module>
    import magic
  File "c:\users\----------\appdata\local\programs\python\python38-32\lib\site-packages\magic.py", line 201, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation`

**Comment by HexNio** [comment]
i think the issue is related to the libmagic module. probably is not correctly installed, i can see you are in a windows machine, the script is developed in a MacOS i think if you try in a linux machine too you will have no problems, i will try to figure out how to fix the issue in the windows machine.

**Comment by ghost** [comment]
i tried a fix for that error (installing another libmagic module version) and did not worked
