### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by chmosama** [HexNio/ssl_pinning_remover#2]
I am trying to run it on my macOS but getting this below error.
`chmosama@Chs-Mac Desktop % ssl_pinning_remover -i world.apk -v      
[+] Cleaning...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/ssl_pinning_remover", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ssl_pinning_remover/ssl_pinning_remover.py", line 64, in main
    unlock_apk(args.input, args.upload)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ssl_pinning_remover/ssl_pinning_remover.py", line 13, in unlock_apk
    output_folder = core.unpack_jar(input_path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ssl_pinning_remover/core/core.py", line 37, in unpack_jar
    output_dir = input_path.rsplit('/',1)[1].rsplit('.', 1)[0]
IndexError: list index out of range`

**Comment by ItsCinnabar** [comment]
His examples line showing "ssl_pinning_remover -i test.apk -v" is wrong. You need to include the entire path to test.apk starting at /

**Comment by bebwong** [comment]
> 他的示例行顯示“ ssl_pinning_remover -i test.apk -v”是錯誤的。您需要包括從/開始的test.apk的完整路徑。
